let numero1 = parseInt(prompt("Informe o primeiro valor: "))
let numero2 = parseInt(prompt("Informe o segundo valor: "))
let numero3 = parseInt(prompt("Informe o terceiro valor: "))
let numero4 = parseInt(prompt("Informe o quarto valor: "))


console.log("TABOADA DE ADIÇÃO")
console.log("=".repeat(40))
console.log(`${numero1} + ${numero2} = ${numero1 + numero2}`)
console.log(`${numero1} + ${numero3} = ${numero1 + numero3}`)
console.log(`${numero1} + ${numero4} = ${numero1 + numero4}`)
console.log(`${numero2} + ${numero3} = ${numero2 + numero3}`)
console.log(`${numero2} + ${numero4} = ${numero2 + numero4}`)
console.log(`${numero3} + ${numero4} = ${numero3 + numero4}`)
console.log("=".repeat(40))

console.log("RESULTADOS DAS MULTIPLICAÇÕES")
console.log("=".repeat(40))
console.log(`${numero1} * ${numero2} = ${numero1 * numero2}`)
console.log(`${numero1} * ${numero3} = ${numero1 * numero3}`)
console.log(`${numero1} * ${numero4} = ${numero1 * numero4}`)
console.log(`${numero2} * ${numero3} = ${numero2 * numero3}`)
console.log(`${numero2} * ${numero4} = ${numero2 * numero4}`)
console.log(`${numero3} * ${numero4} = ${numero3 * numero4}`)
console.log("=".repeat(40))